WITH ORDER_ITEMS_IN_YEAR AS (
  SELECT
    OI.SELLER_ID,
    O.ORDER_ID,
    OI.ORDER_ITEM_ID,
    MONTH(O.ORDER_PURCHASE_TIMESTAMP) AS ORDER_MONTH,
    WEEK(O.ORDER_PURCHASE_TIMESTAMP) AS ORDER_WEEK,
    DAY(O.ORDER_PURCHASE_TIMESTAMP) AS ORDER_DAY
  FROM
    ORDER_ITEMS OI
    LEFT JOIN ORDERS O ON OI.ORDER_ID = O.ORDER_ID
  WHERE
    YEAR(O.ORDER_PURCHASE_TIMESTAMP) = 2017
),
DAILY_ITEMS_PER_SELLER AS (
  SELECT
    ORDER_MONTH,
    ORDER_WEEK,
    ORDER_DAY,
    SELLER_ID,
    COUNT(ORDER_ITEM_ID) AS ORDER_ITEM_COUNTS
  FROM
    ORDER_ITEMS_IN_YEAR
  GROUP BY
    ORDER_MONTH,
    ORDER_WEEK,
    ORDER_DAY,
    SELLER_ID
),
WEEKLY_ACTIVE_SELLERS_COUNTS AS (
  SELECT
    ORDER_MONTH,
    ORDER_WEEK,
    SELLER_ID,
    SUM(ORDER_ITEM_COUNTS) AS WEEKLY_ITEM_COUNTS
  FROM
    DAILY_ITEMS_PER_SELLER
  GROUP BY
    ORDER_MONTH,
    ORDER_WEEK,
    SELLER_ID
  HAVING
    WEEKLY_ITEM_COUNTS >= 5
),
MONTHLY_ACTIVE_SELLERS_COUNTS AS (
  SELECT
    ORDER_MONTH,
    SELLER_ID,
    SUM(ORDER_ITEM_COUNTS) AS MONTHLY_ITEM_COUNTS
  FROM
    DAILY_ITEMS_PER_SELLER
  GROUP BY
    ORDER_MONTH,
    SELLER_ID
  HAVING
    MONTHLY_ITEM_COUNTS >= 25
),
DAILY_ACTIVE_SELLERS AS (
  SELECT
    ORDER_MONTH,
    ORDER_DAY,
    COUNT(SELLER_ID) AS DAILY_ACTIVE_SELLERS
  FROM
    DAILY_ITEMS_PER_SELLER
  GROUP BY
    ORDER_MONTH,
    ORDER_DAY
),
MONTHLY_ACTIVE_SELLERS AS (
  SELECT
    ORDER_MONTH,
    COUNT(SELLER_ID) AS MONTHLY_ACTIVE_SELLERS
  FROM
    MONTHLY_ACTIVE_SELLERS_COUNTS
  GROUP BY
    ORDER_MONTH
),
WEEKLY_ACTIVE_SELLERS AS (
  SELECT
    ORDER_MONTH,
    ORDER_WEEK,
    COUNT(SELLER_ID) AS WEEKLY_ACTIVE_SELLERS
  FROM
    WEEKLY_ACTIVE_SELLERS_COUNTS
  GROUP BY
    ORDER_MONTH,
    ORDER_WEEK
),
AVG_WEEKLY_ACTIVE_SELLERS AS (
  SELECT
    ORDER_MONTH,
    AVG(WEEKLY_ACTIVE_SELLERS) AS AVG_WEEKLY_ACTIVE_SELLERS
  FROM
    WEEKLY_ACTIVE_SELLERS
  GROUP BY
    ORDER_MONTH
),
AVG_DAILY_ACTIVE_SELLERS AS (
  SELECT
    ORDER_MONTH,
    AVG(DAILY_ACTIVE_SELLERS) AS AVG_DAILY_ACTIVE_SELLERS
  FROM
    DAILY_ACTIVE_SELLERS
  GROUP BY
    ORDER_MONTH
)
SELECT
  D.ORDER_MONTH,
  M.MONTHLY_ACTIVE_SELLERS AS MONTHLY_ACTIVE_SELLERS,
  ROUND(W.AVG_WEEKLY_ACTIVE_SELLERS, 2) AS AVG_WEEKLY_ACTIVE_SELLERS,
  ROUND(D.AVG_DAILY_ACTIVE_SELLERS, 2) AS AVG_DAILY_ACTIVE_SELLERS
FROM
  AVG_DAILY_ACTIVE_SELLERS D
  LEFT JOIN AVG_WEEKLY_ACTIVE_SELLERS W ON W.ORDER_MONTH = D.ORDER_MONTH
  LEFT JOIN MONTHLY_ACTIVE_SELLERS M ON M.ORDER_MONTH = D.ORDER_MONTH
ORDER BY
  ORDER_MONTH
